pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Source code checked out by Jenkins'
            }
        }

       stage('Build') {
    steps {
        bat '''
            echo Workspace: %WORKSPACE%
            cd /d "%WORKSPACE%\\Jenkins_pipeline_files\\maven-samples\\single-module"
            echo Current Directory:
            cd
            dir
            mvn clean install
        '''
    }
}

        stage('Test Results') {
            steps {
                junit 'maven-samples/single-module/target/surefire-reports/*.xml'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'maven-samples/single-module/target/*.jar',
                                 allowEmptyArchive: false
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}