pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Source code checked out by Jenkins'
            }
        }

        stage('Build') {
            steps {
                bat '''
                    echo Workspace: %WORKSPACE%
                    cd /d "%WORKSPACE%\\Jenkins_pipeline_files\\maven-samples\\single-module"
                    echo Current Directory:
                    cd
                    dir
                    mvn clean install
                '''
            }
        }

        stage('Test Results') {
            steps {
                junit 'Jenkins_pipeline_files/maven-samples/single-module/target/surefire-reports/*.xml'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'Jenkins_pipeline_files/maven-samples/single-module/target/*.jar',
                                 fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}